### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by StefanThoma** [shafayetShafee/downloadthis#3]
I tried to visit the website at: https://shafayetshafee.github.io/downloadthis/
This did not work (error 404)

**Comment by shafayetShafee** [comment]
My examples are hosted in Github Pages and the correct link is actually https://shafayetshafee.github.io/downloadthis/example.html

Can you try with this link?

**Comment by StefanThoma** [comment]
I see, this works, thanks!
I just followed the `view deployment` link which expects an index.html file somewhere I guess. 
Thanks for the quick response, looks really useful!

**Comment by shafayetShafee** [comment]
@StefanThoma,  Please consider giving a star to this repo if this looks useful 😊.
